MyCard3/Models/Article.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCard3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.ThumbUpNumber = 0;
            this.Comment = new HashSet<Comment>();
            this.ArticleThumberUp = new HashSet<ArticleThumberUp>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime Time { get; set; }
        public string Content { get; set; }
        public int BoardId { get; set; }
        public int PersonId { get; set; }
        public int ThumbUpNumber { get; set; }
        public bool IsOnTop { get; set; }
        public bool IsNoComment { get; set; }
        public bool IsHidden { get; set; }
    
        public virtual Board Board { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleThumberUp> ArticleThumberUp { get; set; }
    }
}

MyCard3/Controllers/ArticlesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MyCard3.Models;


namespace MyCard3.Controllers
{
    [RequireHttps]
    public class ArticlesController : Controller
    {
        private MyCardContainer db = new MyCardContainer();

        [HttpPost, ValidateInput(false)]
        public void EditorTest(string editordata)
        {
            int i = 1;
        }

        public ActionResult HotArticles()
        {
            return PartialView(db.ArticleSet.OrderByDescending(a => a.ThumbUpNumber).Take(10));
        }

        [HttpPost]
        public ActionResult ThumberUp(int articleId)
        {
            int i = 1;
            Person currentUser = Session["CurrentUserData"] as Person;
            Article article = db.ArticleSet.Where(a => a.Id == articleId).FirstOrDefault();
            if (!db.ArticleThumberUpSet.Where(tu => (tu.PersonId == currentUser.Id) && (tu.ArticleId == articleId)).Any())
            {
                db.ArticleThumberUpSet.Add(new ArticleThumberUp { PersonId = currentUser.Id, ArticleId = articleId });
                article.ThumbUpNumber += 1;
                int tmpN = 0;
                switch (article.ThumbUpNumber)
                {
                    case 10:
                        tmpN = 10;
                        break;
                    case 5:
                        tmpN = 5;
                        break;
                    case 1:
                        tmpN = 1;
                        break;
                }
                db.NotificationSet.Add(new Notification { PersonId = article.PersonId, Time = DateTime.Now.ToLocalTime(), Content = $"You got {tmpN} ThumbUp(s) in {article.Title}" });
                db.People.Where(p => p.Id == currentUser.Id).FirstOrDefault().HasNewNotification = true;
                db.SaveChanges();
            }
            return Json(new { n = article.ThumbUpNumber });
        }

        // GET: Articles
        [Authorize]
        public ActionResult Index(int? boardId = 1)
        {
            ////////////// order articles
            var startDate = DateTime.Now.ToLocalTime().AddMonths(-3);
            var articleSet = db.ArticleSet.AsNoTracking().Where(a => a.BoardId == boardId)
                .Where(a =>  (!a.IsHidden && a.Time > startDate) || a.IsOnTop ).ToList();
            articleSet = articleSet.OrderByDescending(a => a.IsOnTop).ThenByDescending(a => a.Time).ToList();
            //////////////
            ViewData["BoardName"] = articleSet.FirstOrDefault().Board.Name;
            ViewData["BoardId"] = articleSet.FirstOrDefault().Board.Id;
            return View(articleSet);
        }

        // GET: Articles/Details/5
        [Authorize]
        [ArticleAuthorAuthorizeAttribute(Roles = "BoardAdmin,ConfirmedUser,ArticleOwner")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Article article = db.ArticleSet.Find(id);
            Article article = db.ArticleSet.AsNoTracking().Where(a => a.Id == id).Include(c => c.Comment).FirstOrDefault();
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // GET: Articles/Create
        [Authorize(Roles = "BoardAdmin,ConfirmedUser")]
        public ActionResult Create(int boardId = 1)
        {
            //ViewBag.BoardId = new SelectList(db.BoardSet, "Id", "Name");
            //ViewBag.PersonId = new SelectList(db.People, "Id", "Name");
            ViewData["BoardId"] = boardId;
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        [Authorize(Roles = "BoardAdmin,ConfirmedUser")]
        public ActionResult Create([Bind(Include = "Id,Title,Content")] Article article, int boardId = 1)
        {
            if (ModelState.IsValid)
            {
                article.Time = DateTime.Now.ToLocalTime();
                var authenticationId = User.Identity.GetUserId();
                article.PersonId = db.People.Where(p => p.authenticationId == authenticationId).FirstOrDefault().Id;
                article.BoardId = boardId;
                db.ArticleSet.Add(article);
                db.SaveChanges();
                return RedirectToAction("Index", new { boardId = article.BoardId });
            }

            //ViewBag.BoardId = new SelectList(db.BoardSet, "Id", "Name", article.BoardId);
            //ViewBag.PersonId = new SelectList(db.People, "Id", "Name", article.PersonId);
            return View(article);
        }

        // GET: Articles/Edit/5
        [ArticleAuthorAuthorizeAttribute(Roles = "BoardAdmin,ArticleOwner")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.ArticleSet.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            ViewBag.BoardId = new SelectList(db.BoardSet, "Id", "Name", article.BoardId);
            ViewBag.PersonId = new SelectList(db.People, "Id", "Name", article.PersonId);
            return View(article);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Time,Content,BoardId,PersonId")] Article article)
        {
            if (ModelState.IsValid)
            {
                db.Entry(article).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BoardId = new SelectList(db.BoardSet, "Id", "Name", article.BoardId);
            ViewBag.PersonId = new SelectList(db.People, "Id", "Name", article.PersonId);
            return View(article);
        }

        // GET: Articles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.ArticleSet.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Article article = db.ArticleSet.Find(id);
            db.ArticleSet.Remove(article);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyCard3/Controllers/BoardsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MyCard3.Models;

namespace MyCard3.Controllers
{
    [RequireHttps]
    public class BoardsController : Controller
    {
        private MyCardContainer db = new MyCardContainer();

        // GET: Boards
        public ActionResult Index()
        {
            //////////////
            //Session["CurrentUserAuthenticationID"] = User.Identity.GetUserId();
            string tmp = User.Identity.GetUserId();
            Person currentUser = db.People.AsNoTracking().Where(p => p.authenticationId == tmp).AsEnumerable().FirstOrDefault();
            Session["CurrentUserData"] = currentUser;
            //////////////
            //if (currentUser != null)
            //{
            //    if (currentUser.HasNewNotification)
            //    {
            //        Session["HasNewNotification"] = true;
            //    }
            //}
            return View(db.BoardSet.ToList());
        }

        // GET: Boards/Details/5
        [Authorize(Roles = "BoardAdmin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Board board = db.BoardSet.Find(id);
            if (board == null)
            {
                return HttpNotFound();
            }
            return View(board);
        }

        // GET: Boards/Create
        [Authorize(Roles = "BoardAdmin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Boards/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "BoardAdmin")]
        public ActionResult Create([Bind(Include = "Id,Name")] Board board)
        {
            if (ModelState.IsValid)
            {
                db.BoardSet.Add(board);
                db.SaveChanges();
                db.ArticleSet.Add(new Article() { Title = "版規", Time = DateTime.Now.ToLocalTime(), BoardId = board.Id, PersonId = 1 });
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(board);
        }

        // GET: Boards/Edit/5
        [Authorize(Roles = "BoardAdmin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Board board = db.BoardSet.Find(id);
            if (board == null)
            {
                return HttpNotFound();
            }
            return View(board);
        }

        // POST: Boards/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "BoardAdmin")]
        public ActionResult Edit([Bind(Include = "Id,Name")] Board board)
        {
            if (ModelState.IsValid)
            {
                db.Entry(board).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(board);
        }

        // GET: Boards/Delete/5
        [Authorize(Roles = "BoardAdmin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Board board = db.BoardSet.Find(id);
            if (board == null)
            {
                return HttpNotFound();
            }
            return View(board);
        }

        // POST: Boards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "BoardAdmin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Board board = db.BoardSet.Find(id);
            db.BoardSet.Remove(board);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyCard3/Views/Articles/Create.cshtml
@model MyCard3.Models.Article

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm(new { boardId = ViewData["BoardId"] }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.BoardId, "BoardId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("BoardId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BoardId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PersonId, "PersonId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("PersonId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PersonId, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@*<form method="post" action="@Url.Action("EditorTest")">
        <textarea id="summernote" name="editordata"></textarea>
        <input type="submit" value="Test" />
    </form>*@

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.js"></script>
    <script>
        $(document).ready(function () {
            $('#Content').summernote();
        });
    </script>

}

MyCard3/Views/Articles/Delete.cshtml
@model MyCard3.Models.Article

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Article</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Board.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Board.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Person.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyCard3/Views/Articles/Details.cshtml
@model MyCard3.Models.Article

@{
    ViewBag.Title = "Details";
}

@*<h2>Details</h2>*@

<div>
    @*<h4>Article</h4>*@
    @*<hr />*@
    <dl class="dl-horizontal">
        <div name="ArticleInfo" class="bg-success text-white">
            <div class="row">
                <div class="col-lg-8">
                    標題: @Html.DisplayFor(model => model.Title) | @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) | @Html.ActionLink("Delete", "Delete", new { id = Model.Id })
                </div>
                <div class="col-lg-4">
                    看板: @Html.DisplayFor(model => model.Board.Name)
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8">作者:@Html.DisplayFor(model => model.Person.Name)</div>
                <div class="col-lg-4">時間:@Html.DisplayFor(model => model.Time)</div>
            </div>
        </div>
        @*
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Person)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Person.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Time)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Time)
            </dd>
        *@

        @*<dt>
                @Html.DisplayNameFor(model => model.Content)
            </dt>*@

        <dd>
            @*@Html.DisplayFor(model => model.Content)*@
            @*@Html.TextAreaFor(model => model.Content)*@
            <div name="ArticleContent" style="background-color: rgb(243, 242, 238)">
                @Html.Raw(Model.Content)
            </div>

        </dd>

        @*<dt>
                @Html.DisplayNameFor(model => model.Board.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Board.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Person.Name)
            </dt>*@

    </dl>
</div>
<div>
    <span id="ArticleThumberUpNumber">
        @Model.ThumbUpNumber
    </span>
    <button type="button" id="btnLike">Like this Article!</button>
</div>


<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |*@
    @Html.ActionLink("Back to List", "Index", new { boardId = Model.BoardId })
</p>
<p>
    @{
        if (!Model.IsNoComment)
        {
            @Html.ActionLink("Create New Comments", "Create", "Comments", new { articleId = Model.Id, personId = Model.PersonId }, null)
        }
    }
</p>
@{
    Html.RenderPartial("~/Views/Comments/CommentList.cshtml", Model.Comment);
}
<p>
    @Html.ActionLink("Back to List", "Index", new { boardId = Model.BoardId })
</p>
@section Scripts {
    <script>
        $(function () {
            $("#btnLike").click(function () {

                $.post("@Url.Action("ThumberUp", "Articles")", { "articleId":@Model.Id }, function (data, textStatus) {

                    $("#ArticleThumberUpNumber").text(data.n)

                    //alert(data.n)
                    //data contains the JSON object
                    //textStatus contains the status: success, error, etc
                }, "json");
            });


                $(".LikeComment").click(function (event) {
                    $.post("@Url.Action("ThumberUp", "Comments")", { "commentId": event.target.id }, function (data, textStatus) {

                        $("#" + event.target.id).text(data.n)

                    //alert(data.n)
                    //data contains the JSON object
                    //textStatus contains the status: success, error, etc
                }, "json");
                });
        });
    </script>
}

MyCard3/Views/Articles/Edit.cshtml
@model MyCard3.Models.Article

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Time, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Time, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*---------------------------------*@
                @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @*---------------------------------*@
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BoardId, "BoardId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BoardId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BoardId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonId, "PersonId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PersonId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PersonId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.js"></script>
    <script>
        $(document).ready(function () {
            $('#Content').summernote();
        });
    </script>
}

MyCard3/Views/Articles/HotArticles.cshtml
@model IEnumerable<MyCard3.Models.Article>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.ThumbUpNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Board.Name)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Person.Name)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Content)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.ThumbUpNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Board.Name)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Person.Name)
        </td>*@
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.Id }) 
        </td>
    </tr>
}

</table>

MyCard3/Views/Articles/Index.cshtml
@model IEnumerable<MyCard3.Models.Article>

@{
    ViewBag.Title = "Index";
}

<h2>@ViewData["BoardName"]</h2>

<p>
    @Html.ActionLink("Create New", "Create",new { BoardId=ViewData["BoardId"] })
</p>
<table class="table">
    @*<tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Person.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Board.Name)
        </th>

        <th></th>
    </tr>*@

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ThumbUpNumber)
            @Html.ActionLink(item.Title, "Details", "Articles", new { Id = item.Id }, null)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Person.Name)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Time)
        </td>*@
        @*<td>
            @Html.Raw(item.Content)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Board.Name)
        </td>*@

        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @*@Html.ActionLink("Details", "Details", new { id=item.Id }) |*@
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
    }

</table>
<div>
    @Html.ActionLink("Back to Boards", "Index", "Boards")
</div>